### PR TITLE
Return the legacy login type (Craft|EE2|BigCommerce) in the ajax resp…

### PR DESCRIPTION
**Pull request by bossanova808**
…onse and http session data.

Call assignUserToDefaultGroup when successfully creating the user.

I couldn't set a variable with setRouteVariables followed by redirectToPostedUrl, so I opted for storing it in session data (I also tried flash data - I couldn't set data with a custome key, and using 'notice' to returns something like 'Logged In (Craft).' seemed messy and would also not survive e.g. another re-direct.

I figure there are use cases where they might want to hang on to how the user logged in for e.g. onboarding purposes like 'On our old site you did this, now do ....this instead' 

Also, I have added calls to assign the user to the default group as part of the user creation which I believe is standard practise for plugins creating users.

### CODE REVIEW

**Comment by bossanova808** [comment]
Oh I haven't updated versions/docs etc as I thought I's see what you thought first :)

**Comment by bossanova808** [comment]
Hi Michael

Any thoughts on this one?

**Comment by michaelrog** [comment]
Looks good — thanks!

(Next time please PR against the `dev` branch.)

**Comment by bossanova808** [comment]
Yep sorry will do (especially now you and Andrew have both told me ;)

**Pull request merged**
